#!/usr/bin/env bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

### 更新节点流量统计
### QQ133814250

parentDir=/var/www/html/openvpn_api
fileName=$2
dirAndName="/var/www/html/openvpn_api/disconnect.php"
rm -rf $dirAndName
if [ ! -d "$parentDir" ];then
echo "父级文件夹路径错误"
else
cd $parentDir

if [ ! -f "$dirAndName" ];then
cat >> $dirAndName <<"EOFF"
<?php
require(dirname(dirname(__FILE__))."/system.php");
$fee = 1.35;
$username = $argv[1];
@$s = sprintf("%.0f",$argv[2]*$fee);
@$r = sprintf("%.0f",$argv[3]*$fee);
$db = db(_openvpn_);
$uinfo = $db->where(array(_iuser_=>$username))->find();
$new_s = $uinfo[_isent_] + $s;
$new_r = $uinfo[_irecv_] + $r;

/**
 * @Notes:
 * 获取本机ip
 * @Interface get_local_ip
 * @author [MengShuai] [<133814250@qq.com>]
 */
function get_local_ip()
{
    $result = sendRequest('http://bufan.ms521.cn/index/line/location', [], $method = 'GET');
    return isset(json_decode($result['msg'],true)['data']['ip']) ? json_decode($result['msg'],true)['data']['ip'] : '127.0.0.1';
}



/**
 * @Notes:
 * 发送CURL
 * @Interface sendRequest
 * @author [MengShuai] [<133814250@qq.com>]
 */
function sendRequest($url, $params = [], $method = 'POST', $options = [])
{
    $method = strtoupper($method);
    $protocol = substr($url, 0, 5);
    $query_string = is_array($params) ? http_build_query($params) : $params;

    $ch = curl_init();
    $defaults = [];
    if ('GET' == $method) {
        $geturl = $query_string ? $url . (stripos($url, "?") !== false ? "&" : "?") . $query_string : $url;
        $defaults[CURLOPT_URL] = $geturl;
    } else {
        $defaults[CURLOPT_URL] = $url;
        if ($method == 'POST') {
            $defaults[CURLOPT_POST] = 1;
        } else {
            $defaults[CURLOPT_CUSTOMREQUEST] = $method;
        }
        $defaults[CURLOPT_POSTFIELDS] = $query_string;
    }

    $defaults[CURLOPT_HEADER] = false;
    $defaults[CURLOPT_USERAGENT] = "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.98 Safari/537.36";
    $defaults[CURLOPT_FOLLOWLOCATION] = true;
    $defaults[CURLOPT_RETURNTRANSFER] = true;
    $defaults[CURLOPT_CONNECTTIMEOUT] = 3;
    $defaults[CURLOPT_TIMEOUT] = 3;

    // disable 100-continue
    curl_setopt($ch, CURLOPT_HTTPHEADER, array('Expect:'));

    if ('https' == $protocol) {
        $defaults[CURLOPT_SSL_VERIFYPEER] = false;
        $defaults[CURLOPT_SSL_VERIFYHOST] = false;
    }

    curl_setopt_array($ch, (array)$options + $defaults);

    $ret = curl_exec($ch);
    $err = curl_error($ch);

    if (false === $ret || !empty($err)) {
        $errno = curl_errno($ch);
        $info = curl_getinfo($ch);
        curl_close($ch);
        return [
            'ret'   => false,
            'errno' => $errno,
            'msg'   => $err,
            'info'  => $info,
        ];
    }
    curl_close($ch);
    return [
        'ret' => true,
        'msg' => $ret,
    ];
}



db(_openvpn_)->where(["id"=>$uinfo["id"]])->update(["online"=>0]);
if($new_r+$new_s > $uinfo[_maxll_]){
	//流量不足 禁用此用户
	$db->where(array("id"=>$uinfo["id"]))->update(array(_i_=>"0"));
}
$c = $s+$r;
if($db->where(array("id"=>$uinfo["id"]))->update(array(_isent_=>$new_s,_irecv_=>$new_r)))
{
	//更新用户数据并且更新排行榜数据
	$db2 = db('top');
	$u = $db2->where(array('username'=>$username,'time'=>date('Y-m-d',time())))->find();
	if($u){
		$new = $u['data']+$c;
		$db2->where(array('id'=>$u['id']))->update(array('data'=>$new));
	}else{
		$db2->insert(array('username'=>$username,'data'=>$c,'time'=>date('Y-m-d',time())));
	}
	//db("session")->where(["username"=>$username])->delete();
}


if($uinfo){
    //更新用户使用记录
    $db2 = db('use_log');
    $u = $db2->where(array('ip' => get_local_ip(),'username'=>$username,'time'=>date('Y-m-d',time())))->find();
    if($u){
        $new = $u['data']+$c;
        $db2->where(array('id'=>$u['id']))->update(['data'=>$new, 'count' => 1+$u['count'] ,'last_time' => time()]);
    }else{
        $db2->insert(array('ip' => get_local_ip(),'username'=>$username,'data'=>$c,'time'=>date('Y-m-d',time()), 'count' => 1 ,'last_time' => time()));
    }
}
EOFF
echo "更新节点流量统计 - 成功"
else
echo "文件已经存在"
fi

fi